kind: ConfigMap
apiVersion: v1
metadata:
  name: servingruntimes-config
data:
  override-config: |
      apiVersion: serving.kserve.io/v1alpha1
      kind: ServingRuntime
      metadata:
        name: torchserve-0.x
        labels:
          name: modelmesh-serving-torchserve-0.x-SR
      spec:
        supportedModelFormats:
          - name: pytorch-mar
            version: "0"
            autoSelect: true

        multiModel: true

        grpcEndpoint: "port:8085"
        grpcDataEndpoint: "port:7070"

        containers:
          - name: torchserve
            image: image: pytorch/torchserve:0.6.0-cpu
            args:
              # Adapter creates the config file; wait for it to exist before starting
              - while [ ! -e "$TS_CONFIG_FILE" ]; do echo "waiting for config file..."; sleep 1; done;
              - exec
              - torchserve
              - --start
              - --foreground
            env:
              - name: TS_CONFIG_FILE
                value: /models/_torchserve_models/mmconfig.properties
              # TBD, this may give better performance
              #- name: TS_PREFER_DIRECT_BUFFER
              #  value: true
              # Additional TS_ prefixed TorchServe config options may be added here
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: "5"
                memory: 1Gi
        builtInAdapter:
          serverType: torchserve
          runtimeManagementPort: 7071
          memBufferBytes: 134217728
          modelLoadingTimeoutMillis: 90000