---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhods-catalog-dev
spec:
  displayName: Red Hat OpenShift Data Science
  publisher: RHODS Development Catalog
  image: quay.io/cfchase/rhods-operator-live-catalog:1.22.0-w5
  sourceType: grpc
  secrets:
  - local-quay
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhods-operator-dev
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator-dev
spec:
  name: rhods-operator
  channel: beta
  source: rhods-catalog-dev
  sourceNamespace: redhat-ods-operator
