apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: watson-runtime
  annotations:
    enable-route: "true"
    enable-auth: "false"
spec:
  #imagePullSecrets:
    #- name: custom-registry-secret
    #- name: ibm-entitlement-key
  containers:
  - env:
      - name: ACCEPT_LICENSE
        value: "true"
      - name: LOG_LEVEL
        value: info
      - name: CAPACITY
        value: "28000000000"
      - name: DEFAULT_MODEL_SIZE
        value: "1773741824"
      - name: METRICS_PORT
        value: "2113"
      - name: GATEWAY_PORT
        value: "8060"
      - name: STRICT_RPC_MODE
        value: "false"
      - name: HF_HOME
        value: "/tmp/"
      #- name: USE_EMBEDDED_PULLER
      #  value: 'true'
    image: us.icr.io/watson-runtime/fmaas-runtime-wisdom-ansible:0.0.8
    imagePullPolicy: IfNotPresent
    name: runtime
    resources:
      limits:
        cpu: 2
        memory: 12Gi
      requests:
        cpu: 1
        memory: 5Gi
  grpcDataEndpoint: port:8085
  grpcEndpoint: port:8085
  multiModel: true
  storageHelper:
    disabled: false
  supportedModelFormats:
    - autoSelect: true
      name: watson