apiVersion: v1
kind: ConfigMap
metadata:
  name: apicurio-configmap
data:
  keycloak-url:  https://${KEYCLOAK_URL}/auth
  apicurio-ui-logout-redirect-uri: /
  apicurio-ui-hub-ui-url: https://${APICURIO_URL}/
  apicurio-ui-hub-api-url: https://${APICURIO_API_URL}
  apicurio-ui-editing-url: wss://${APICURIO_WS_URL}
  apicurio-microcks-api-url:  https://${MICROCKS_URL}/api
  apicurio-db-connection-url: jdbc:mysql://apicuriodb:3306/apicuriodb
  apicurio-kc-realm: ${APICURIO_KC_REALM}
  apicurio-kc-client-id: ${APICURIO_KC_CLIENT_ID}
  apicurio-microcks-client-id: ${MICROCKS_KC_CLIENT_ID}
  apicurio-ui-feature-share-with-everyone: 'true'
  apicurio-ui-feature-microcks: 'true'