kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apicuriodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: ${STORAGE_CLASS_NAME}      


