apiVersion: v1
kind: Secret
metadata:
  name: apicurio-secret
type: Opaque
stringData:
  db-password: $DB_PW
  db-root-password: $DB_ROOT_PW
  db-user: $DB_USER
  apicurio-kc-client-secret: $APICURIO_KC_CLIENT_SECRET
  apicurio-microcks-client-secret: $MICROCKS_KC_CLIENT_SECRET