apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.kubernetes.io/name: {{ include "nfs-provisioner.name" . }}
    helm.sh/chart: {{ include "nfs-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.namespace | default ( .Release.Namespace ) }}
spec:
  finalizers:
  - kubernetes
