kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: {{ .Values.storageclass.name }}
provisioner: {{ .Values.storageclass.provisioner }}
parameters:
  mountOptions: {{ .Values.storageclass.mountOptions | quote }}

