apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nfs-provisioner-operator
  template:
    metadata:
      labels:
        name: nfs-provisioner-operator
    spec:
      serviceAccountName: nfs-provisioner-operator
      containers:
        - name: nfs-provisioner-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nfs-provisioner-operator"
