kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: leader-locking-{{ include "nfs-provisioner.name" . }}
  namespace: {{ .Values.namespace | default (.Release.Namespace) }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

