apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount | default (include "nfs-provisioner.name" .) }}
  namespace: {{ .Values.namespace | default (.Release.Namespace) }}
  labels:
    app.kubernetes.io/name: {{ include "nfs-provisioner.name" . }}
    helm.sh/chart: {{ include "nfs-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
