apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chat-client-android
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-client
        version: android
    spec:
      containers:
      - image: docker.io/ljhiyh/chat-client:android
        imagePullPolicy: Always
        name: chat-client
        ports:
        - containerPort: 4200
        volumeMounts:
          - name: chat-client-env
            mountPath: /home/external
      volumes:
        - name: chat-client-env
          configMap:
            name: chat-client-env

