apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chat-server
spec:
  gateways:
  - chat-gateway
  hosts:
  -  %CHAT_SERVER_HOSTNAME%
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: chat-server
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chat-client
spec:
  gateways:
  - chat-gateway
  hosts:
  - %CHAT_CLIENT_HOSTNAME%
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: chat-client
        subset: v1
