apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:  
  name: microcks
  namespace: ${PROJECT_NAME}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: microcks
  source: community-operators
  sourceNamespace: openshift-marketplace