apiVersion: v1
kind: Service
metadata:
  name: jenkins-enterprise
spec:
  ports:
  - name: 8080-TCP
    port: 8080
    protocol: 8080
    targetPort: 8080
  selector:
    application: java-app
  type: LoadBalancer
